### ISSUE TITLE
Using functions not from libssh interface?

### ISSUE THREAD

**Issue by hdnn** [zhengjiezxxy/SftpServer#1]
As I see, you use libssh source files (you link */src/ folder in CMakeLists.txt) to work with **sftp_reply_names_add**, **sftp_reply_name** and other function, that not included in library interface. It's seems like bad solution. 
Maybe after feew month after commit you know why this functions declared without LIBSSH_API macro or you have solution just with functions from library interface?
Anyway, thank you for your work)

**Comment by zhengjiezxxy** [comment]
I have asked the libssh author why sftp_reply_names_add is not in the interface, and he said there maybe some update in the future, anyway you can use them for free now. Anyway I will keep an eye on that.
